# Generated by Django 4.2.7 on 2023-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
